### ISSUE TITLE
Uninitialized Constant breaking Rails console

### ISSUE THREAD

**Issue by AHaymond** [pyromaniac/active_data#10]
After updating to ActiveData 0.3.0 I am now receiving the following error when trying to run `rails c`:

`/vendor/bundle/ruby/2.1.0/bundler/gems/active_data-10a2aef9bd81/lib/active_data/model/primary.rb:6:in '<module:Primary>': uninitialized constant ActiveData::UUID (NameError)`

**Comment by pyromaniac** [comment]
Thanks for your report, didn't know if somebody uses this. Also there are a lot of breaking changes in the latest master, I'm working on it. Mostly now model by default includes just a couple of modules, everything else you have to include manually. Lego bricks :)

**Comment by pyromaniac** [comment]
This issue is fixed btw
