### ISSUE TITLE
NoMethodError: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by igorkasyanchuk** [pyromaniac/active_data#20]
Not always, but sometimes I can see in my Airbrake

https://www.dropbox.com/s/mh5zvnl4zcyjs8o/Screenshot%202015-11-16%2022.24.24.png?dl=0

Params: { "action": "index",   "controller": "search" }

Code:
https://www.dropbox.com/s/i3g0yqw79tt588g/Screenshot%202015-11-16%2022.25.23.png?dl=0

Don't know how to reproduce. I can add something like "obj || {}" and make PR, but I think issue is different

If you will tell me how to reproduce and suggest dirrectio how to fix - I can make PR

**Comment by pyromaniac** [comment]
Could you post an exception itself please?

**Comment by pyromaniac** [comment]
Actually, try `ContentSearch.new(params[:search].presence || {})`

**Comment by pyromaniac** [comment]
Possible reproducing method: `ContentSearch.new(nil)`

**Comment by igorkasyanchuk** [comment]
Exception: https://gist.github.com/igorkasyanchuk/91ea62d49b6176864faf

I can't reproduce with you examples. Also app works in production. In development I never saw such  error.

**Comment by pyromaniac** [comment]
This is a stacktrace, but I need a message

**Comment by igorkasyanchuk** [comment]
Message is "NoMethodError: undefined method `each' for nil:NilClass"

**Comment by pyromaniac** [comment]
try to use `ContentSearch.new(params[:search].presence || {})`

**Comment by igorkasyanchuk** [comment]
it doesn't help, or at least I can't see the difference, because even if I put `nil` search works and I don't see crash (on production just tried).

so with `nil`, or `{}` I can't reproduce the issue.

I just know that it happens from time to time (maybe once per week). So just strange.

I'm using Ruby 2.2.2p95, and Passenger for prod., Rails 4.2.4

**Comment by pyromaniac** [comment]
Frankly, have no ideas except those one. 
Are you sure you have tried `ContentSearch.new(nil)` ? Because it should definitely raise this exception.

**Comment by igorkasyanchuk** [comment]
yes, I tried. And restarted server with touch tmp/restart.txt. Also tried locally in dev mode. Everything works.

**Comment by pyromaniac** [comment]
Weird
