### ISSUE TITLE
alias_method_chain is being deprecated in Rails 5.0

### ISSUE THREAD

**Issue by mattmenefee** [pyromaniac/active_data#22]
When testing my app against the latest Rails 5.0 beta, I noticed a deprecation warning being called within active_data:

> DEPRECATION WARNING: alias_method_chain is deprecated. Please, use Module#prepend instead. From module, you can access the original method using super. (called from block in <module:Callbacks> at /lib/active_data/model/callbacks.rb:48)

I'm not sure that I have the dev chops to open a pull request to fix this, but thought I should bring it to your attention in the event that you were not aware. Thanks!

**Comment by pyromaniac** [comment]
Thanks

**Comment by ACPK** [comment]
+1

**Comment by pyromaniac** [comment]
#25
